name: check-shell
on:
  push:
    branches: [ main ]
jobs:
  test-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run shell
        run: chmod +x ./setup.sh && ./setup.sh